{% set name = 'bob.bio.base' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - verify.py         = bob.bio.base.script.verify:main
    - resources.py      = bob.bio.base.script.resources:resources
    - databases.py      = bob.bio.base.script.resources:databases
    - evaluate.py       = bob.bio.base.script.evaluate:main
    - collect_results.py = bob.bio.base.script.collect_results:main
    - grid_search.py    = bob.bio.base.script.grid_search:main
    - preprocess.py     = bob.bio.base.script.preprocess:main
    - extract.py        = bob.bio.base.script.extract:main
    - enroll.py         = bob.bio.base.script.enroll:main
    - score.py          = bob.bio.base.script.score:main
    - fuse_scores.py    = bob.bio.base.script.fuse_scores:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.blitz
    - bob.core
    - bob.db.base
    - bob.extension
    - bob.io.base
    - bob.learn.activation
    - bob.learn.em
    - bob.learn.linear
    - bob.math
    - bob.measure
    - bob.sp
    - scipy {{ scipy }}
  run:
    - python
    - setuptools
    - scipy

test:
  imports:
    - {{ name }}
  commands:
    - verify.py --help
    - resources.py --help
    - databases.py --help
    - evaluate.py --help
    - collect_results.py --help
    - grid_search.py --help
    - preprocess.py --help
    - extract.py --help
    - enroll.py --help
    - score.py --help
    - fuse_scores.py --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Tools for running biometric recognition experiments
  license_family: BSD
