{% set name = 'bob.bio.base' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.blitz
    - bob.core
    - bob.extension >5.0.1
    - bob.io.base    
    - bob.measure
    - bob.pipelines
    - tabulate {{ tabulate }}
    - pandas {{ pandas }}
    - scipy {{ scipy }}
    - six {{ six }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('tabulate') }}
    - {{ pin_compatible('pandas') }}
    - {{ pin_compatible('scipy') }}
    - {{ pin_compatible('six') }}

test:
  imports:
    - {{ name }}
  commands:
    - bob bio --help
    - bob bio annotate --help
    - bob bio metrics --help
    - bob bio roc --help
    - bob bio det --help
    - bob bio epc --help
    - bob bio hist --help
    - bob bio cmc --help
    - bob bio dir --help
    - bob bio gen --help
    - bob bio evaluate --help
    - bob bio sort --help
    - bob bio pipeline simple --help
    - bob bio pipeline score-norm --help
    - bob bio pipeline transform --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - matplotlib {{ matplotlib }}
    - bob.io.image
    - bob.db.atnt
    - gridtk

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Tools for running biometric recognition experiments
  license_family: BSD
